version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data/var/lib/clickhouse
      - ./init_clickhouse:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_DB=weather
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=pass123

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data/data
  # prefect:
  #   image: prefecthq/prefect:2.10.0-python3.10
  #   container_name: prefect
  #   restart: unless-stopped
  #   command: prefect server start
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./flows:/opt/prefect/flows
  #   environment:
  #     - PREFECT_API_URL=http://0.0.0.0:4200/api

volumes:
  clickhouse_data:
  minio_data:
  prefect_data:
